Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)
  VpcId:
    Description: Specify the VPC for the instance deployment
    Type: String
    Default: vpc-8fe3deeb
  PrivateSubnet:
    Description: Deploy Instance in a specific Subnet
    Type: String
    Default: subnet-81d20ae6
  Ec2SecurityGroup:
    Description: List of Security Groups
    Type: String
    Default: sg-ff713199
  SSHKey:
    Description: SSH Key Pair to use
    Type: String
    Default: jenkins
Mappings:
  RegionMap:
    us-east-1:
      "AmazonLinux" : "ami-80861296" # Ubuntu 16.04 ubuntu-xenial-16.04-amd64-server 2017
    us-east-2:
      "AmazonLinux" : "ami-4191b524" # Amazon AMI Apr 2017
    us-west-1:
      "AmazonLinux" : "ami-02eada62" # Amazon AMI Apr 2017
    us-west-2:
      "AmazonLinux" : "ami-4836a428" # Amazon AMI Apr 2017
    ca-central-1:
      "AmazonLinux" : "ami-0bd66a6f" # Amazon AMI Apr 2017
  InstanceSize:
    SMALL:
      "EC2" : "t2.small"
    MEDIUM:
      "EC2" : "t2.medium"
    LARGE:
      "EC2" : "t2.large"
Resources:
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AmazonLinux]
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: !Ref SSHKey
      SubnetId: !Ref PrivateSubnet
      Tags:
        -
          Key: "Name"
          Value: "web-us-west-1"
      SecurityGroupIds:
        - !Ref Ec2SecurityGroup
      BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              DeleteOnTermination: "false"
              VolumeSize: "100"
            UserData:
      Fn::Base64: !Sub |
          yum update -y
          yum install -y httpd24 php56 mysql55-server php56-mysqlnd
          service httpd start
          chkconfig httpd on
          groupadd www
          usermod -a -G www ec2-user
          chown -R root:www /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} +
          find /var/www -type f -exec chmod 0664 {} +
          echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref EC2
